/**
 * JoCar Automóviles — Datos centrales del stock
 * Fuente de verdad compartida por stock.js y vehiculo.js
 */

const CAR_DATA = [
    {
        id: 'vw-touareg-rline',
        title: 'Volkswagen Touareg R-Line',
        subtitle: '3.0 TDI V6 286CV 4MOTION 8-velocidades',
        marca: 'volkswagen',
        modelo: 'Touareg',
        combustible: 'diesel',
        año: 2022,
        km: 45000,
        precio: 55900,
        cv: 286,
        cilindrada: '3.0',
        cambio: 'Automático',
        traccion: '4MOTION (4x4)',
        puertas: 5,
        plazas: 5,
        color: 'Plata Tungsten Metallic',
        ivaDed: true,
        images: [
            { src: null, alt: 'Volkswagen Touareg R-Line exterior frontal' },
            { src: null, alt: 'Volkswagen Touareg R-Line interior' },
            { src: null, alt: 'Volkswagen Touareg R-Line lateral' }
        ],
        description: 'Volkswagen Touareg R-Line en estado impecable. Equipado con el potente motor V6 TDI de 286CV y tracción integral 4MOTION permanente. Este SUV premium combina un diseño elegante con prestaciones excepcionales. IVA deducible incluido en el precio.',
        specs: {
            'Potencia': '286 CV',
            'Par motor': '600 Nm',
            'Motor': 'V6 TDI 3.0',
            'Aceleración 0-100': '6,1 s',
            'Velocidad máx.': '241 km/h',
            'Consumo mixto': '7,1 l/100km',
            'Emisiones CO₂': '187 g/km',
            'Transmisión': 'Automático 8 vel.',
            'Tracción': '4MOTION 4x4',
            'Carrocería': 'SUV',
            'Largo / Ancho': '4.878 / 1.984 mm',
            'Puertas': '5',
            'Plazas': '5',
        },
        equipment: {
            'Confort & Tecnología': [
                'Volkswagen Digital Cockpit Pro (15")',
                'Pantalla táctil 15" con navegación Discover Pro',
                'Head-Up Display',
                'Keyless Access (entrada sin llave)',
                'Climatizador 4 zonas',
                'Asientos delanteros con calefacción y ventilación',
                'Asiento del conductor con masaje',
                'Sensores de párking delanteros y traseros',
                'Cámara 360° Area View',
                'Carga inalámbrica para smartphone',
                'Apple CarPlay / Android Auto',
                'Interfaz gestual (control por gestos)',
            ],
            'Seguridad': [
                'Front Assist con detección de peatones',
                'Lane Assist (mantenimiento de carril)',
                'Adaptive Cruise Control (ACC)',
                'Frenada de emergencia autónoma',
                'Reconocimiento de señales de tráfico',
                'Sistema de visión nocturna',
                'Detector de fatiga',
                'Control de tracción 4MOTION',
            ],
            'Exterior & Diseño': [
                'Faros Matrix IQ.LIGHT LED',
                'Llantas 21" R-Line',
                'Techo panorámico deslizante',
                'Retrovisores plegables eléctricamente',
                'Portón trasero manos libres',
                'Para-choques R-Line',
                'Suspensión neumática adaptativa',
            ],
            'Audio & Entretenimiento': [
                'Sistema Dynaudio Excellence 16 altavoces',
                'Radio digital DAB+',
                'Bluetooth multiconexión',
                '4 puertos USB-C',
            ],
        }
    },
    {
        id: 'audi-q7-sline',
        title: 'Audi Q7 S-Line',
        subtitle: '3.0 TDI Quattro 286CV 8-velocidades — 7 Plazas',
        marca: 'audi',
        modelo: 'Q7',
        combustible: 'diesel',
        año: 2021,
        km: 60000,
        precio: 62900,
        cv: 286,
        cilindrada: '3.0',
        cambio: 'Automático',
        traccion: 'Quattro (4x4)',
        puertas: 5,
        plazas: 7,
        color: 'Gris Daytona Nacarado',
        ivaDed: true,
        images: [
            { src: null, alt: 'Audi Q7 S-Line exterior frontal' },
            { src: null, alt: 'Audi Q7 S-Line interior' },
            { src: null, alt: 'Audi Q7 S-Line 3ª fila' }
        ],
        description: 'Audi Q7 S-Line 7 plazas en excelente estado. Equipado con la tracción integral Quattro y motor V6 TDI de 286CV. La versión S-Line aporta un acabado deportivo exterior e interior de gran nivel. Ideal para familias que buscan espacio y lujo sin renunciar a las prestaciones.',
        specs: {
            'Potencia': '286 CV',
            'Par motor': '600 Nm',
            'Motor': 'V6 TDI 3.0',
            'Aceleración 0-100': '6,3 s',
            'Velocidad máx.': '241 km/h',
            'Consumo mixto': '7,3 l/100km',
            'Emisiones CO₂': '193 g/km',
            'Transmisión': 'Tiptronic 8 vel.',
            'Tracción': 'Quattro 4x4',
            'Carrocería': 'SUV',
            'Largo / Ancho': '5.063 / 1.968 mm',
            'Puertas': '5',
            'Plazas': '7',
        },
        equipment: {
            'Confort & Tecnología': [
                'Audi Virtual Cockpit Plus (12,3")',
                'MMI Navigation Plus con pantalla 10,1"',
                'Head-Up Display',
                'Climatizador 4 zonas',
                'Asientos delanteros calefactados y ventilados',
                'Tercera fila de asientos (2 plazas)',
                'Keyless Entry & Go',
                'Cámara trasera con líneas dinámicas',
                'Sensores de aparcamiento 360°',
                'Techo panorámico de cristal fijo',
                'Apple CarPlay / Android Auto',
                'Carga inalámbrica Qi',
            ],
            'Seguridad': [
                'Audi Pre sense front & city',
                'Adaptive Cruise Control',
                'Lane Departure Warning',
                'Detección de peatones y ciclistas',
                'Frenada de emergencia autónoma',
                'Control de punto ciego',
                'Alerta de tráfico cruzado trasero',
            ],
            'Exterior S-Line': [
                'Faros Matrix LED con indicadores dinámicos',
                'Llantas 21" S-Line',
                'Paragolpes S-Line delantero y trasero',
                'Umbrales iluminados S-Line',
                'Suspensión deportiva S-Line',
                'Retrovisores exteriores plegables eléctricamente',
                'Portón trasero eléctrico manos libres',
            ],
            'Audio': [
                'Bang & Olufsen 3D Premium Sound System (730W)',
                'Sonido surround 3D con altavoces en reposacabezas',
                'Radio digital DAB+',
            ],
        }
    },
    {
        id: 'bmw-x3-xdrive',
        title: 'BMW X3 xDrive20d',
        subtitle: '2.0 TDI 190CV xDrive Automático 8 vel.',
        marca: 'bmw',
        modelo: 'X3',
        combustible: 'diesel',
        año: 2021,
        km: 75000,
        precio: 41900,
        cv: 190,
        cilindrada: '2.0',
        cambio: 'Automático',
        traccion: 'xDrive (4x4)',
        puertas: 5,
        plazas: 5,
        color: 'Azul Phytonic Metallic',
        ivaDed: true,
        images: [
            { src: '../assets/car7_bmw_x3.webp', alt: 'BMW X3 xDrive20d exterior' },
            { src: null, alt: 'BMW X3 xDrive20d interior' },
            { src: null, alt: 'BMW X3 xDrive20d maletero' }
        ],
        description: 'BMW X3 xDrive20d en impecable estado. Motor diésel de 190CV con tracción integral xDrive y cambio automático de 8 velocidades. Equipamiento Live Cockpit Connected con todos los paquetes de asistencia a la conducción. Revisiones en concesionario oficial BMW.',
        specs: {
            'Potencia': '190 CV',
            'Par motor': '400 Nm',
            'Motor': '4 cil. TDI 2.0',
            'Aceleración 0-100': '7,6 s',
            'Velocidad máx.': '218 km/h',
            'Consumo mixto': '5,3 l/100km',
            'Emisiones CO₂': '140 g/km',
            'Transmisión': 'Steptronic 8 vel.',
            'Tracción': 'xDrive 4x4',
            'Carrocería': 'SUV',
            'Largo / Ancho': '4.716 / 1.891 mm',
            'Puertas': '5',
            'Plazas': '5',
        },
        equipment: {
            'Confort & Tecnología': [
                'Live Cockpit Connected (pantalla 12,3")',
                'Navegación Professional iDrive 7',
                'BMW Head-Up Display',
                'Climatizador automático 2 zonas',
                'Asientos Sport calefactados',
                'Keyless Entry',
                'Cámara trasera',
                'Sensores parking delante y detrás',
                'Techo panorámico Sky Lounge',
                'Wireless Apple CarPlay',
                'Carga inalámbrica smartphone',
                'Maletero automático manos libres',
            ],
            'Paquete de conducción': [
                'Driving Assistance Pack',
                'Lane Departure Warning',
                'Active Cruise Control con Stop&Go',
                'Colisión y arranque del vehículo delantero',
                'Reconocimiento de señales de tráfico',
                'Asistente de cambio de carril',
                'Cámara lateral',
                'Parking Assistant',
            ],
            'Exterior': [
                'Faros adaptativos LED',
                'Llantas 19" doble radio',
                'Paquete Shadowline (embellecedores negros)',
                'Retrovisores plegables eléctricamente',
                'Barras de techo nativas',
                'Suspensión Sport',
            ],
            'Audio': [
                'Sistema HiFi profesional Harman Kardon',
                'Radio digital DAB+',
                'Bluetooth & 2 × USB-C',
            ],
        }
    },
    {
        id: 'mercedes-g63-amg',
        title: 'Mercedes-Benz G 63 AMG',
        subtitle: 'V8 Biturbo 585CV 4MATIC+ TCT9 — Edición Especial',
        marca: 'mercedes',
        modelo: 'Clase G',
        combustible: 'gasolina',
        año: 2020,
        km: 85000,
        precio: 159000,
        cv: 585,
        cilindrada: '4.0',
        cambio: 'Automático',
        traccion: '4MATIC+ (4x4)',
        puertas: 5,
        plazas: 5,
        color: 'Negro Obsidiana Metallic',
        ivaDed: false,
        images: [
            { src: '../assets/car6_g63.webp', alt: 'Mercedes G63 AMG exterior' },
            { src: null, alt: 'Mercedes G63 AMG interior AMG' },
            { src: null, alt: 'Mercedes G63 AMG detalle motor' }
        ],
        description: 'Espectacular Mercedes G 63 AMG en estado excepcional. Solo 85.000 km y full equipo de fábrica. Motor V8 biturbo de 585CV con sonido único de escape AMG Performance. La leyenda del todoterreno en su versión más potente y exclusiva. Vehículo sin IVA.',
        specs: {
            'Potencia': '585 CV',
            'Par motor': '850 Nm',
            'Motor': 'V8 Biturbo 4.0',
            'Aceleración 0-100': '4,5 s',
            'Velocidad máx.': '220 km/h (limitada)',
            'Consumo mixto': '13,1 l/100km',
            'Emisiones CO₂': '299 g/km',
            'Transmisión': 'AMG SPEEDSHIFT TCT 9G',
            'Tracción': '4MATIC+ Permanente',
            'Carrocería': 'SUV',
            'Largo / Ancho': '4.624 / 1.984 mm',
            'Puertas': '5',
            'Plazas': '5',
        },
        equipment: {
            'AMG Performance': [
                'Motor AMG 4.0L V8 Biturbo 585CV',
                'AMG SPEEDSHIFT TCT 9G automático',
                'AMG Performance Exhaust (escape deportivo)',
                'Sistema de diferencial AMG en eje trasero',
                'Frenos AMG de alto rendimiento (discos perforados)',
                'Suspensión AMG RIDE CONTROL+',
                'Modos de conducción AMG DYNAMIC SELECT',
            ],
            'Interior de lujo': [
                'Asientos de cuero Nappa AMG Performance',
                'Panel de instrumentos AMG (dos pantallas 12,3")',
                'Volante AMG Sport multifunción calefactado',
                'Iluminación ambiental 64 colores',
                'Sistema de audio Burmester® de alta gama',
                'Climatizador 4 zonas',
                'Techo interior Alcantara',
                'Pedales en acero inoxidable AMG',
            ],
            'Tecnología': [
                'MBUX (Mercedes-Benz User Experience)',
                'Navegación Live Traffic',
                'Head-Up Display',
                'Sistema de cámara 360°',
                'Keyless Go',
                'Carga inalámbrica',
                'Apple CarPlay / Android Auto',
                'Módulo telemático Car2x',
            ],
            'Exterior': [
                'Faros MULTIBEAM LED adaptativos',
                'Llantas AMG 22" bicolor',
                'Pinzas de freno AMG en rojo',
                'Protección de bajos en negro AMG',
                'Estriberas tubulares de acero AMG',
                'Spare wheel (rueda de repuesto trasera)',
            ],
        }
    },
    {
        id: 'mini-jcw',
        title: 'Mini John Cooper Works',
        subtitle: '2.0 Turbo 231CV Automático 8 vel.',
        marca: 'mini',
        modelo: 'Mini JCW',
        combustible: 'gasolina',
        año: 2021,
        km: 34000,
        precio: 32900,
        cv: 231,
        cilindrada: '2.0',
        cambio: 'Automático',
        traccion: 'Delantera',
        puertas: 3,
        plazas: 4,
        color: 'Rojo Chile Metallic',
        ivaDed: true,
        images: [
            { src: '../assets/car4_mini_jcw.webp', alt: 'Mini JCW exterior' },
            { src: null, alt: 'Mini JCW interior deportivo' },
            { src: null, alt: 'Mini JCW detalles JCW' }
        ],
        description: 'Mini JCW en estado excelente con solo 34.000 km. Motor 2.0 litros turbo de 231CV con cambio automático Steptronic de 8 velocidades. El Mini más emocionante con acabado JCW completo: asientos deportivos, escape deportivo, sistema de frenado John Cooper Works y toda la electrónica de última generación.',
        specs: {
            'Potencia': '231 CV',
            'Par motor': '320 Nm',
            'Motor': '4 cil. Turbo 2.0',
            'Aceleración 0-100': '6,1 s',
            'Velocidad máx.': '250 km/h',
            'Consumo mixto': '7,0 l/100km',
            'Emisiones CO₂': '160 g/km',
            'Transmisión': 'Steptronic 8 vel.',
            'Tracción': 'Delantera',
            'Carrocería': 'Hatchback 3 puertas',
            'Largo / Ancho': '3.821 / 1.727 mm',
            'Puertas': '3',
            'Plazas': '4',
        },
        equipment: {
            'JCW Performance': [
                'Motor 2.0 Turbo 231CV John Cooper Works',
                'Sistema de escape JCW con sonido sport',
                'Suspensión deportiva JCW',
                'Frenos JCW (discos ventilados sobredimensionados)',
                'Modos de conducción (Green/Mid/Sport/Track)',
                'Control launch (salida de parrilla)',
                'Diferencial de deslizamiento limitado JCW',
            ],
            'Interior JCW': [
                'Asientos JCW Recaro con apoyo lateral',
                'Volante JCW sport de cuero calefactado',
                'Cuadro de instrumentos MINI con anillo central LED',
                'Climatizador automático',
                'Pantalla táctil 8,8" con navegación',
                'Apple CarPlay & Android Auto',
                'Bluetooth & USB',
                'Calefacción de asientos traseros',
            ],
            'Exterior': [
                'Faros Full LED adaptativos',
                'Llantas JCW 18" Negro Carbono',
                'Techo negro brillante',
                'Espejos Sport en negro brillante',
                'Spoiler trasero JCW',
                'Difusor trasero JCW',
                'Insignias JCW exclusivas',
            ],
            'Tecnología': [
                'MINI Connected con navegación en vivo',
                'Cámara de visión trasera',
                'Sensores de aparcamiento traseros',
                'Control de velocidad adaptativo',
                'Frenada de emergencia autónoma',
            ],
        }
    },
    {
        id: 'vw-tiguan-rline',
        title: 'Volkswagen Tiguan R Line',
        subtitle: '2.0 TDI 150CV DSG 7 velocidades',
        marca: 'volkswagen',
        modelo: 'Tiguan',
        combustible: 'diesel',
        año: 2022,
        km: 99300,
        precio: 31900,
        cv: 150,
        cilindrada: '2.0',
        cambio: 'Automático',
        traccion: 'Delantera',
        puertas: 5,
        plazas: 5,
        color: 'Blanco Puro',
        ivaDed: true,
        images: [
            { src: '../assets/car8_tiguan.webp', alt: 'Volkswagen Tiguan R Line exterior' },
            { src: null, alt: 'Volkswagen Tiguan R Line interior' },
            { src: null, alt: 'Volkswagen Tiguan R Line maletero' }
        ],
        description: 'Volkswagen Tiguan R Line con acabado deportivo. Motor 2.0 TDI 150CV con caja DSG de doble embrague y 7 velocidades. El equipamiento R-Line incluye elementos exteriores e interiores exclusivos que le dan un aspecto más agresivo. IVA deducible incluido.',
        specs: {
            'Potencia': '150 CV',
            'Par motor': '340 Nm',
            'Motor': '4 cil. TDI 2.0',
            'Aceleración 0-100': '8,7 s',
            'Velocidad máx.': '208 km/h',
            'Consumo mixto': '5,5 l/100km',
            'Emisiones CO₂': '145 g/km',
            'Transmisión': 'DSG 7 vel.',
            'Tracción': 'Delantera',
            'Carrocería': 'SUV',
            'Largo / Ancho': '4.527 / 1.839 mm',
            'Puertas': '5',
            'Plazas': '5',
        },
        equipment: {
            'Confort & Tecnología': [
                'Volkswagen Digital Cockpit (10,25")',
                'Discover Media navegación 9,2"',
                'Climatizador automático 2 zonas',
                'Asientos calefactados delanteros',
                'Keyless Entry & Go',
                'Cámara trasera',
                'Sensores de aparcamiento traseros y delanteros',
                'Techo panorámico corredizo',
                'Apple CarPlay / Android Auto',
                'Carga inalámbrica',
                'Maletero Easy Open',
            ],
            'Seguridad': [
                'Front Assist con frenada de emergencia',
                'Lane Assist',
                'Side Assist (punto ciego)',
                'Rear Traffic Alert',
                'Adaptive Cruise Control',
                'Emergency Assist',
            ],
            'R-Line Exclusivo': [
                'Paragolpes R-Line delantero y trasero',
                'Llantas 19" R-Line bicolor',
                'Umbrales iluminados R-Line',
                'Asientos R-Line con tapizado Artvelour',
                'Volante R-Line multifunción en cuero',
                'Suspensión deportiva R-Line',
            ],
        }
    },
    {
        id: 'peugeot-rifter-gt',
        title: 'Peugeot Rifter GT',
        subtitle: '1.5 BlueHDi 130CV EAT8 — 7 Plazas',
        marca: 'peugeot',
        modelo: 'Rifter',
        combustible: 'diesel',
        año: 2019,
        km: 149000,
        precio: 16900,
        cv: 130,
        cilindrada: '1.5',
        cambio: 'Automático',
        traccion: 'Delantera',
        puertas: 5,
        plazas: 7,
        color: 'Gris Platinium Metallic',
        ivaDed: true,
        images: [
            { src: '../assets/car1_rifter.webp', alt: 'Peugeot Rifter GT exterior' },
            { src: null, alt: 'Peugeot Rifter GT 7 plazas' },
            { src: null, alt: 'Peugeot Rifter GT interior' }
        ],
        description: 'Peugeot Rifter GT 7 plazas con cambio automático EAT8, ideal para familias numerosas. Motor BlueHDi 130CV limpio y eficiente. Acabado GT con cuadro de instrumentos i-Cockpit, asistentes de conducción avanzados y modular interior para el máximo aprovechamiento del espacio.',
        specs: {
            'Potencia': '130 CV',
            'Par motor': '300 Nm',
            'Motor': '4 cil. BlueHDi 1.5',
            'Aceleración 0-100': '10,9 s',
            'Velocidad máx.': '185 km/h',
            'Consumo mixto': '5,0 l/100km',
            'Emisiones CO₂': '130 g/km',
            'Transmisión': 'EAT8 automático',
            'Tracción': 'Delantera',
            'Carrocería': 'Monovolumen',
            'Largo / Ancho': '4.403 / 1.848 mm',
            'Puertas': '5',
            'Plazas': '7',
        },
        equipment: {
            'Familia & Versatilidad': [
                '7 plazas modulares (3 filas)',
                'Puertas traseras correderas (apertura manos libres)',
                'Techo panorámico de cristal fijo',
                'Compartimentos de almacenamiento Moduwork',
                'Cuadro i-Cockpit con volante compacto',
                'Climatizador automático bizona',
                'Calefacción de asientos 1ª y 2ª fila',
            ],
            'Tecnología': [
                'Pantalla táctil Peugeot i-Connect 10"',
                'Navegación con tráfico en tiempo real',
                'Apple CarPlay / Mirror Screen',
                'Cámara trasera + cámaras laterales',
                'Sensor de párking 360°',
                'Control de velocidad adaptativo',
                'Reconocimiento de señales',
            ],
            'GT Exclusivo': [
                'Llantas 17" GT bicolor',
                'Pinzas de freno en rojo GT',
                'Tapicería GT bicolor',
                'Barras de techo longitudinales',
                'Faros Full LED Matrix',
                'Paragolpes GT con detalles de aluminio',
            ],
        }
    },
    {
        id: 'peugeot-3008-hdi',
        title: 'Peugeot 3008 HDI',
        subtitle: '1.5 BlueHDi 130CV GT Line Automático',
        marca: 'peugeot',
        modelo: '3008',
        combustible: 'diesel',
        año: 2021,
        km: 130000,
        precio: 16900,
        cv: 130,
        cilindrada: '1.5',
        cambio: 'Automático',
        traccion: 'Delantera',
        puertas: 5,
        plazas: 5,
        color: 'Azul Magnetic Metallic',
        ivaDed: true,
        images: [
            { src: '../assets/car5_3008.webp', alt: 'Peugeot 3008 HDI exterior' },
            { src: null, alt: 'Peugeot 3008 HDI i-Cockpit' },
            { src: null, alt: 'Peugeot 3008 HDI maletero' }
        ],
        description: 'Peugeot 3008 GT Line con motor BlueHDi 130CV y cambio automático EAT8. Premio al mejor coche del año en su generación. El i-Cockpit con pantalla de información de cabeza arriba y cuadro de instrumentos digital supone una experiencia de conducción única. Precio muy competitivo para su equipamiento.',
        specs: {
            'Potencia': '130 CV',
            'Par motor': '300 Nm',
            'Motor': '4 cil. BlueHDi 1.5',
            'Aceleración 0-100': '10,4 s',
            'Velocidad máx.': '193 km/h',
            'Consumo mixto': '4,6 l/100km',
            'Emisiones CO₂': '121 g/km',
            'Transmisión': 'EAT8 automático',
            'Tracción': 'Delantera',
            'Carrocería': 'SUV',
            'Largo / Ancho': '4.447 / 1.841 mm',
            'Puertas': '5',
            'Plazas': '5',
        },
        equipment: {
            'Confort': [
                'i-Cockpit con pantalla cuadro instrumento 12,3"',
                'Pantalla táctil i-Connect 10"',
                'Head-Up Display',
                'Climatizador automático 2 zonas',
                'Asientos calefactados delanteros',
                'Techo panorámico Horizon',
                'Apertura de maletero manos libres',
                'Asiento del conductor con masaje',
            ],
            'Seguridad': [
                'Frenada emergencia activa con detección peatones',
                'Control de crucero adaptativo con Stop&Go',
                'Mantenimiento de carril activo',
                'Vigilancia de ángulo muerto',
                'Cámara de marcha atrás HD',
                'Sensor de párking delantero y trasero',
                'Alerta de somnolencia',
            ],
            'GT Line': [
                'Llantas 19" GT Line bicolor negro',
                'Faros Full LED',
                'Detalles exteriores cromados negros',
                'Tapicería GT Line con detalles en gris',
                'Pedalera en aluminio',
                'Parrilla frontal GT Line específica',
            ],
            'Conectividad': [
                'Apple CarPlay / Android Auto',
                'MirrorLink',
                'Carga inalámbrica',
                '3 × USB, 1 × USB-C',
                'Wi-Fi integrado 4G',
            ],
        }
    }
];

// Utilidad: encontrar coche por ID
function getCarById(id) {
    return CAR_DATA.find(c => c.id === id) || null;
}

// Utilidad: coches similares (mismo combustible o mismo rango de precio ±30%)
function getSimilarCars(car, max = 4) {
    return CAR_DATA
        .filter(c => c.id !== car.id)
        .map(c => {
            let score = 0;
            if (c.combustible === car.combustible) score += 2;
            if (c.marca === car.marca) score += 3;
            const priceDiff = Math.abs(c.precio - car.precio) / car.precio;
            if (priceDiff < 0.3) score += 2;
            if (priceDiff < 0.15) score += 2;
            return { car: c, score };
        })
        .sort((a, b) => b.score - a.score)
        .slice(0, max)
        .map(x => x.car);
}
